"""campos time adicionados

Revision ID: 0af004f0fb6c
Revises: a3483b8bf8c4
Create Date: 2022-06-01 22:04:18.983007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af004f0fb6c'
down_revision = 'a3483b8bf8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('date_doing', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('date_done', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('time_spend', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('time_estimated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'time_estimated')
    op.drop_column('task', 'time_spend')
    op.drop_column('task', 'date_done')
    op.drop_column('task', 'date_doing')
    # ### end Alembic commands ###
