"""initial

Revision ID: 607adc45deca
Revises: 
Create Date: 2022-06-01 23:20:00.792335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607adc45deca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_doing', sa.DateTime(), nullable=True),
    sa.Column('date_done', sa.DateTime(), nullable=True),
    sa.Column('time_spend', sa.String(length=20), nullable=True),
    sa.Column('time_estimated', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
